//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HeavyDuck.DF.DwarfDuck.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HeavyDuck.DF.DwarfDuck.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap arrow_circle_double {
            get {
                object obj = ResourceManager.GetObject("arrow_circle_double", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap dwarves {
            get {
                object obj = ResourceManager.GetObject("dwarves", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap gender {
            get {
                object obj = ResourceManager.GetObject("gender", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap gender_female {
            get {
                object obj = ResourceManager.GetObject("gender_female", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to graphics_dwarves
        ///
        ///[OBJECT:GRAPHICS]
        ///
        ///[TILE_PAGE:DWARVES]
        ///  [FILE:dwarves.png]
        ///  [TILE_DIM:18:18]
        ///  [PAGE_DIM:16:9]
        ///
        ///[CREATURE_GRAPHICS:DWARF]
        ///  [STANDARD:DWARVES:0:0:AS_IS:DEFAULT]
        ///  [DEFAULT:DWARVES:0:0:ADD_COLOR:DEFAULT]
        ///  [CHILD:DWARVES:1:0:AS_IS:DEFAULT]
        ///  [BABY:DWARVES:2:0:AS_IS:DEFAULT]
        ///
        ///  [SLAVE:DWARVES:3:0:AS_IS:DEFAULT]
        ///  [PRISONER:DWARVES:4:0:AS_IS:DEFAULT]
        ///
        ///  [MINER:DWARVES:5:0:AS_IS:DEFAULT]
        ///  [STONEWORKER:DWARVES:6:0:AS_IS:DEFAULT]
        ///  [ENGRAVER:DWARVES:7:0:AS_IS:DEFAULT]
        ///  [ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string graphics_dwarves {
            get {
                return ResourceManager.GetString("graphics_dwarves", resourceCulture);
            }
        }
    }
}
